# 1 Introduction {-}

## 1.1 Purpose {-}
This chapter describes the Code of Ordinances ("Code") and the scope of the Code's application to the Tahoe region. 

## 1.2 Short Title {-}
The Code of Ordinances may be cited and referred to as the "Code." 

## 1.3 Overview of Organization of the Code of Ordinances {-}
This section summarizes the contents of the Code of Ordinances in a brief, user-friendly format.  This overview section is intended solely as a guide for administrative officials and the public to use in understanding the organization of the Code.  

This Code is divided into nine divisions, each of which contains one or more chapters.  The divisions are organized as outlined below.  Not all individual Code chapters are addressed in this summary overview.

### 1.3.1 General Provisions (Chapters 1 through 6) {-}
This division contains materials that are generally applicable and useful for administering and understanding the entire Code of Ordinances.  In addition to this introduction to the Code (which includes descriptions of the documents that support the Code of Ordinances), major features of this division include:

