# 2 Applicability {-}

## 2.1 General Provisions {-}

### 2.1.1 Purpose {-}
This chapter implements the Compact provisions relating to projects and permits.  This chapter also implements Article VI(a) of the Compact, which requires TRPA to prescribe by ordinance those activities that the agency has determined will not have a substantial effect on the land, water, air, space, or any other natural resources in the Tahoe region and therefore are exempt from the agency’s review and approval. 

### 2.1.2 Applicability {-}
This chapter identifies activities that may have a substantial effect on the land, air, water, space or any other natural resources and therefore are projects subject to TRPA review and approval.  This chapter also identifies activities that will not have a substantial effect on the land, air, water, space and any other natural resource in the region and therefore are exempt from TRPA review and approval.  Exemption of activities from TRPA review and approval shall not be construed to exempt such activities from applicable provisions of the Code.  Special applicability provisions for signs and for activities in the shorezone are set forth in Chapters 38 and 80.

### 2.1.3 Organization of this chapter {-}
A.	Section 2.2 implements the Compact provisions relating to projects and permits.  An activity that is not exempt or granted a qualified exemption from this Code pursuant to Section 2.3 is a project subject to TRPA review and approval pursuant to Section 2.2.

B.	Section 2.3 identifies activities that will not have a substantial effect on the land, air, water, space, or any other natural resources in the Tahoe region and therefore are exempt or are eligible for a qualified exemption from TRPA review and approval.  Exemption or qualified exemption of activities from TRPA review and approval shall not be construed to exempt such activities from other applicable provisions of the Code.  
