# 4 Required Findings {-}

## 4.1. PURPOSE {-}
The Tahoe Regional Planning Compact requires TRPA to make findings before taking certain actions.  In addition, the Regional Plan package, including the Code and plan area statements, sets forth other findings that must be made.  This chapter sets forth procedures describing how TRPA shall make the findings required.

## 4.2.	APPLICABILITY {-}
Prior to approving any project or taking any other action specified in this Code, TRPA shall make the findings required by the provisions of the Regional Plan package, including the Goals and Policies, the Code, and specifically this chapter and any other requirement of law.  All such findings shall be made in accordance with this chapter.

## 4.3 PROCEDURE FOR FINDINGS {-}
Findings shall be made as provided below. 

### 4.3.1.	Written Findings {-}
All required findings shall be in writing and shall be supported by substantial evidence in the record of review.  The findings required by Section 4.4 shall be in writing prior to the approval of the proposed matter.

### 4.3.2.	Statement {-}
Required findings shall be accompanied by a brief statement of the facts and rationales upon which they are based.
