# 5 Compliance {-}

## 5.1.	PURPOSE {-}

This chapter provides enforcement mechanisms concerning project applications, project approvals, conditions of approval, provisions of the Compact, Goals and Policies, and the Code of Ordinances

## 5.2.	APPLICABILITY {-}
This chapter applies to all projects and activities.  As used in this chapter, the term "provisions of law" means provisions of the Compact, Goals and Policies, and Code.

## 5.3.	PROJECT INSPECTIONS {-}
Projects approved by TRPA shall be subject to inspections by TRPA at any reasonable time.  The permittee shall be responsible for making the project area accessible for inspection purposes.  TRPA shall not be liable for any expense incurred by the permittee as a result of TRPA inspections.

### 5.3.1.	Required Inspection {-}

TRPA shall conduct the following inspections, as appropriate:

A.	For projects that require grading, TRPA shall conduct a pregrading inspection to determine if the permittee has satisfied pregrading conditions of approval, including installation of temporary erosion control and vegetation protection, and construction site boundary fencing.  Other than actions to satisfy pregrading conditions of approval, no grading or construction shall be undertaken in the project area by the permittee until TRPA has notified the permittee that, based on the pregrading inspection, TRPA has verified that the pregrading conditions of approval have been satisfied.

