# 6 Tracking, Accounting, & Banking {-}

## 6.1.	PURPOSE {-}
The purpose of this chapter is to monitor development and to relate activities and projects on parcels to the development allocation and transfer provisions of the Code.  This chapter sets forth the standards and procedures for a tracking and accounting system of basic data regarding each parcel of land, allocations, and land banks.

## 6.2.	APPLICABILITY {-}
TRPA shall maintain for all parcels, allocations, and land banks, as public information, the data required by this chapter.  All TRPA actions shall be consistent with this data.

## 6.3.	GENERAL PROVISIONS {-}

### 6.3.1.	Responsibility for Tracking and Accounting System {-}
TRPA shall be responsible for establishing and maintaining a tracking and accounting system.  TRPA shall coordinate record-keeping efforts with local governments and land banks established pursuant to this chapter.  TRPA shall integrate the tracking and accounting system with environmental threshold maintenance efforts to minimize duplication of data gathering and processing.  (See Chapter 16: Regional Plan and Environmental Threshold Review.)

### 6.3.2.	Coordination and Cooperation with Land Banking Programs {-}
TRPA shall develop and implement a program for coordinating files and data tracking systems with land banks.  Land bank files shall be audited not less than once a year by TRPA to assure data base accuracy and consistency with TRPA files.

### 6.3.3.	Accounting and Crediting Limitations {-}
Land coverage and units of use subject to allocation or transfer limitations may be removed from a parcel and credited for future use pursuant to the Code.  Land coverage and units of use may be credited to the parcel account if such coverage or units are verified by TRPA as legally existing on or after October 15, 1986.

